%%{init:{'flowchart':{'useMaxWidth':true,'htmlLabels':true}}}%%
flowchart TD
  B[["new TenYun(...)"]]-.->S0[[api]]
  B-.->S1[["..."]]
  B-.->S2[[tcb]]
  B-.->S3[[waf]]
  S0-.->S00[["DescribeProducts()"]]
  S0-.->S01[["...(...)"]]
  S1-.->S10[["...(...)"]]
  S2-.->S20[["BindEnvGateway(...)"]]
  S2-.->S21[["...(...)"]]
  S3-.->S30[["...(...)"]]
  S3-.->S31[["UpsertSession(...)"]]
  S00-.->E[["AxiosPromise&lt;Response extends object&gt;"]]
  S01-.->E
  S10-.->E
  S20-.->E
  S21-.->E
  S30-.->E
  S31-.->E
  E-.->T[["&lt;T extends Response&gt;then({data: T})"]]
  subgraph G [ ]
    subgraph api [ ]
      S0
      S00
      S01
    end
    subgraph ... [ ]
      S1
      S10
    end
    subgraph tcb [ ]
      S2
      S20
      S21
    end
    subgraph waf [ ]
      S3
      S30
      S31
    end
    E
  end
  classDef dashed fill:none,stroke-dasharray:5 5
  class G,api,tcb,...,waf dashed

%% npx -p @mermaid-js/mermaid-cli mmdc -i sdk-flowchart.mmd -o sdk-flowchart.svg
%% sed -i '' 's/max-width: 1361.48px; //' sdk-flowchart.svg
